<div class="container">
    <div class="row">
        <div class="col-md-4 offset-md-4">
            <form action="/admin" method="post" id="login_admin">
                <div class="form-group">
                    <label for="exampleInputEmail1">Username</label>
                    <input type="text" class="form-control" id="username" name="username" aria-describedby="emailHelp" placeholder="username">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Password</label>
                    <input type="password" class="form-control" id="password" name="password" placeholder="password">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
<script>
    $('#login_admin').submit(function (event) {
        event.preventDefault();
        let data = {};
        data['username'] = $('#username').val();
        data['password'] = $('#password').val();
        remote('admin', 'login', successLogin, data);
    });
    function successLogin(content){
        console.log(content);
        if(content != 0){
            location.reload();
        }
    }
</script>
